CREATE OR REPLACE TABLE TELCO_RA.MARTS.DIM_CUSTOMER AS SELECT * FROM TELCO_RA.STAGING.DIM_CUSTOMER;
CREATE OR REPLACE TABLE TELCO_RA.MARTS.DIM_PLAN     AS SELECT * FROM TELCO_RA.STAGING.DIM_PLAN;
CREATE OR REPLACE TABLE TELCO_RA.MARTS.DIM_DATE     AS SELECT * FROM TELCO_RA.STAGING.DIM_DATE;